// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/sensors.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/emgeorrk/pulse/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCPUSource is a mock of CPUSource interface.
type MockCPUSource struct {
	ctrl     *gomock.Controller
	recorder *MockCPUSourceMockRecorder
	isgomock struct{}
}

// MockCPUSourceMockRecorder is the mock recorder for MockCPUSource.
type MockCPUSourceMockRecorder struct {
	mock *MockCPUSource
}

// NewMockCPUSource creates a new mock instance.
func NewMockCPUSource(ctrl *gomock.Controller) *MockCPUSource {
	mock := &MockCPUSource{ctrl: ctrl}
	mock.recorder = &MockCPUSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCPUSource) EXPECT() *MockCPUSourceMockRecorder {
	return m.recorder
}

// Ticks mocks base method.
func (m *MockCPUSource) Ticks() ([]entity.CoreTicks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ticks")
	ret0, _ := ret[0].([]entity.CoreTicks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ticks indicates an expected call of Ticks.
func (mr *MockCPUSourceMockRecorder) Ticks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ticks", reflect.TypeOf((*MockCPUSource)(nil).Ticks))
}

// MockMemSource is a mock of MemSource interface.
type MockMemSource struct {
	ctrl     *gomock.Controller
	recorder *MockMemSourceMockRecorder
	isgomock struct{}
}

// MockMemSourceMockRecorder is the mock recorder for MockMemSource.
type MockMemSourceMockRecorder struct {
	mock *MockMemSource
}

// NewMockMemSource creates a new mock instance.
func NewMockMemSource(ctrl *gomock.Controller) *MockMemSource {
	mock := &MockMemSource{ctrl: ctrl}
	mock.recorder = &MockMemSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemSource) EXPECT() *MockMemSourceMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockMemSource) Read() (entity.MemStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(entity.MemStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockMemSourceMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockMemSource)(nil).Read))
}

// MockNetSource is a mock of NetSource interface.
type MockNetSource struct {
	ctrl     *gomock.Controller
	recorder *MockNetSourceMockRecorder
	isgomock struct{}
}

// MockNetSourceMockRecorder is the mock recorder for MockNetSource.
type MockNetSourceMockRecorder struct {
	mock *MockNetSource
}

// NewMockNetSource creates a new mock instance.
func NewMockNetSource(ctrl *gomock.Controller) *MockNetSource {
	mock := &MockNetSource{ctrl: ctrl}
	mock.recorder = &MockNetSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetSource) EXPECT() *MockNetSourceMockRecorder {
	return m.recorder
}

// Counters mocks base method.
func (m *MockNetSource) Counters() ([]entity.NetCounters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counters")
	ret0, _ := ret[0].([]entity.NetCounters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Counters indicates an expected call of Counters.
func (mr *MockNetSourceMockRecorder) Counters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counters", reflect.TypeOf((*MockNetSource)(nil).Counters))
}

// MockDiskSource is a mock of DiskSource interface.
type MockDiskSource struct {
	ctrl     *gomock.Controller
	recorder *MockDiskSourceMockRecorder
	isgomock struct{}
}

// MockDiskSourceMockRecorder is the mock recorder for MockDiskSource.
type MockDiskSourceMockRecorder struct {
	mock *MockDiskSource
}

// NewMockDiskSource creates a new mock instance.
func NewMockDiskSource(ctrl *gomock.Controller) *MockDiskSource {
	mock := &MockDiskSource{ctrl: ctrl}
	mock.recorder = &MockDiskSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskSource) EXPECT() *MockDiskSourceMockRecorder {
	return m.recorder
}

// IOTotals mocks base method.
func (m *MockDiskSource) IOTotals() (uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IOTotals")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IOTotals indicates an expected call of IOTotals.
func (mr *MockDiskSourceMockRecorder) IOTotals() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IOTotals", reflect.TypeOf((*MockDiskSource)(nil).IOTotals))
}

// Usage mocks base method.
func (m *MockDiskSource) Usage() (entity.DiskUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage")
	ret0, _ := ret[0].(entity.DiskUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Usage indicates an expected call of Usage.
func (mr *MockDiskSourceMockRecorder) Usage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockDiskSource)(nil).Usage))
}

// MockTempSource is a mock of TempSource interface.
type MockTempSource struct {
	ctrl     *gomock.Controller
	recorder *MockTempSourceMockRecorder
	isgomock struct{}
}

// MockTempSourceMockRecorder is the mock recorder for MockTempSource.
type MockTempSourceMockRecorder struct {
	mock *MockTempSource
}

// NewMockTempSource creates a new mock instance.
func NewMockTempSource(ctrl *gomock.Controller) *MockTempSource {
	mock := &MockTempSource{ctrl: ctrl}
	mock.recorder = &MockTempSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTempSource) EXPECT() *MockTempSourceMockRecorder {
	return m.recorder
}

// Temps mocks base method.
func (m *MockTempSource) Temps() ([]entity.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Temps")
	ret0, _ := ret[0].([]entity.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Temps indicates an expected call of Temps.
func (mr *MockTempSourceMockRecorder) Temps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Temps", reflect.TypeOf((*MockTempSource)(nil).Temps))
}

// MockVoltSource is a mock of VoltSource interface.
type MockVoltSource struct {
	ctrl     *gomock.Controller
	recorder *MockVoltSourceMockRecorder
	isgomock struct{}
}

// MockVoltSourceMockRecorder is the mock recorder for MockVoltSource.
type MockVoltSourceMockRecorder struct {
	mock *MockVoltSource
}

// NewMockVoltSource creates a new mock instance.
func NewMockVoltSource(ctrl *gomock.Controller) *MockVoltSource {
	mock := &MockVoltSource{ctrl: ctrl}
	mock.recorder = &MockVoltSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoltSource) EXPECT() *MockVoltSourceMockRecorder {
	return m.recorder
}

// Voltages mocks base method.
func (m *MockVoltSource) Voltages() ([]entity.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Voltages")
	ret0, _ := ret[0].([]entity.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Voltages indicates an expected call of Voltages.
func (mr *MockVoltSourceMockRecorder) Voltages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Voltages", reflect.TypeOf((*MockVoltSource)(nil).Voltages))
}

// MockFanSource is a mock of FanSource interface.
type MockFanSource struct {
	ctrl     *gomock.Controller
	recorder *MockFanSourceMockRecorder
	isgomock struct{}
}

// MockFanSourceMockRecorder is the mock recorder for MockFanSource.
type MockFanSourceMockRecorder struct {
	mock *MockFanSource
}

// NewMockFanSource creates a new mock instance.
func NewMockFanSource(ctrl *gomock.Controller) *MockFanSource {
	mock := &MockFanSource{ctrl: ctrl}
	mock.recorder = &MockFanSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFanSource) EXPECT() *MockFanSourceMockRecorder {
	return m.recorder
}

// Fans mocks base method.
func (m *MockFanSource) Fans() ([]entity.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fans")
	ret0, _ := ret[0].([]entity.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fans indicates an expected call of Fans.
func (mr *MockFanSourceMockRecorder) Fans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fans", reflect.TypeOf((*MockFanSource)(nil).Fans))
}

// MockBatterySource is a mock of BatterySource interface.
type MockBatterySource struct {
	ctrl     *gomock.Controller
	recorder *MockBatterySourceMockRecorder
	isgomock struct{}
}

// MockBatterySourceMockRecorder is the mock recorder for MockBatterySource.
type MockBatterySourceMockRecorder struct {
	mock *MockBatterySource
}

// NewMockBatterySource creates a new mock instance.
func NewMockBatterySource(ctrl *gomock.Controller) *MockBatterySource {
	mock := &MockBatterySource{ctrl: ctrl}
	mock.recorder = &MockBatterySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatterySource) EXPECT() *MockBatterySourceMockRecorder {
	return m.recorder
}

// Battery mocks base method.
func (m *MockBatterySource) Battery() (entity.BatteryStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Battery")
	ret0, _ := ret[0].(entity.BatteryStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Battery indicates an expected call of Battery.
func (mr *MockBatterySourceMockRecorder) Battery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Battery", reflect.TypeOf((*MockBatterySource)(nil).Battery))
}

// MockGPUSource is a mock of GPUSource interface.
type MockGPUSource struct {
	ctrl     *gomock.Controller
	recorder *MockGPUSourceMockRecorder
	isgomock struct{}
}

// MockGPUSourceMockRecorder is the mock recorder for MockGPUSource.
type MockGPUSourceMockRecorder struct {
	mock *MockGPUSource
}

// NewMockGPUSource creates a new mock instance.
func NewMockGPUSource(ctrl *gomock.Controller) *MockGPUSource {
	mock := &MockGPUSource{ctrl: ctrl}
	mock.recorder = &MockGPUSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUSource) EXPECT() *MockGPUSourceMockRecorder {
	return m.recorder
}

// GPU mocks base method.
func (m *MockGPUSource) GPU() (entity.GPUStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPU")
	ret0, _ := ret[0].(entity.GPUStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GPU indicates an expected call of GPU.
func (mr *MockGPUSourceMockRecorder) GPU() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPU", reflect.TypeOf((*MockGPUSource)(nil).GPU))
}

// MockPowerSource is a mock of PowerSource interface.
type MockPowerSource struct {
	ctrl     *gomock.Controller
	recorder *MockPowerSourceMockRecorder
	isgomock struct{}
}

// MockPowerSourceMockRecorder is the mock recorder for MockPowerSource.
type MockPowerSourceMockRecorder struct {
	mock *MockPowerSource
}

// NewMockPowerSource creates a new mock instance.
func NewMockPowerSource(ctrl *gomock.Controller) *MockPowerSource {
	mock := &MockPowerSource{ctrl: ctrl}
	mock.recorder = &MockPowerSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerSource) EXPECT() *MockPowerSourceMockRecorder {
	return m.recorder
}

// Power mocks base method.
func (m *MockPowerSource) Power() (entity.PowerStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Power")
	ret0, _ := ret[0].(entity.PowerStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Power indicates an expected call of Power.
func (mr *MockPowerSourceMockRecorder) Power() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Power", reflect.TypeOf((*MockPowerSource)(nil).Power))
}

// MockFreqSource is a mock of FreqSource interface.
type MockFreqSource struct {
	ctrl     *gomock.Controller
	recorder *MockFreqSourceMockRecorder
	isgomock struct{}
}

// MockFreqSourceMockRecorder is the mock recorder for MockFreqSource.
type MockFreqSourceMockRecorder struct {
	mock *MockFreqSource
}

// NewMockFreqSource creates a new mock instance.
func NewMockFreqSource(ctrl *gomock.Controller) *MockFreqSource {
	mock := &MockFreqSource{ctrl: ctrl}
	mock.recorder = &MockFreqSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFreqSource) EXPECT() *MockFreqSourceMockRecorder {
	return m.recorder
}

// Frequency mocks base method.
func (m *MockFreqSource) Frequency() (entity.FreqStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Frequency")
	ret0, _ := ret[0].(entity.FreqStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Frequency indicates an expected call of Frequency.
func (mr *MockFreqSourceMockRecorder) Frequency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Frequency", reflect.TypeOf((*MockFreqSource)(nil).Frequency))
}
